export const DELETE_DEVICE = "DELETE_DEVICE";
export const CHANGE_DEVICE_NAME = "CHANGE_DEVICE_NAME";
export const CHANGE_DEVICE_DESCRIPTION = "CHANGE_DEVICE_DESCRIPTION";
export const UPDATE_FILE_DOWNLOAD_LINKS = "UPDATE_FILE_DOWNLOAD_LINKS";
