export const TOGGLE_IS_LOADING = "TOGGLE_IS_LOADING";
export const CHANGE_DEVICELIST = "CHANGE_DEVICELIST";
export const GET_DEVICELIST = "GET_DEVICELIST";
export const CHANGE_COMMAND_LOG = "CHANGE_COMMAND_LOG";
export const TOGGLE_ADD_DEVICE_SUCCESS_MODAL =
  "TOGGLE_ADD_DEVICE_SUCCESS_MODAL";
export const ADD_NEW_DEVICE_DETAIL = "ADD_NEW_DEVICE_DETAIL";
